# This is a basic workflow to help you get started with Actions

name: Auto Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, add-electron-build ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_and_deploy_to_pages:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
    # Set Up Node
    - name: Setup Node.js
      uses: actions/setup-node@v1.4.2

    # Runs a set of commands using the runners shell
    - name: Build with GDexport
      run: |
        git clone https://github.com/arthuro555/gdexporter
        cd gdexporter
        rm -rf Project
        git clone https://github.com/Gdevelop-game/GDevelop-Open-Game Project
        npm i
        npm link
        gdexport -b -p "./Project/src/game.json"
      
    - name: Upload to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2.0.1
      with:
        # Build directory to deploy
        build_dir: gdexporter/Exported
        # The committer name and email address
        committer: Auto Builder
        # Commit message
        commit_message: Auto Built nightly game build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
  build_for_pc:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        
    steps:
      
      - name: Build with GDexport
        run: |
          git clone https://github.com/arthuro555/gdexporter
          cd gdexporter
          rm -rf Project
          git clone https://github.com/Gdevelop-game/GDevelop-Open-Game Project
          npm i
          node bin/cli.js -b electron -p "./Project/src/game.json"
          
      - name: Build Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}
          app_root: gdexporter/Exported
          package_root: gdexporter/Exported
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          # Upload all potential executables
          path: gdexporter/Exported/dist/*.*
